spring:
  profiles:
    active: local # 기본 active profile 설정

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: ${LOCAL_MYSQL_URL}
    username: ${LOCAL_MYSQL_USER}
    password: ${LOCAL_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always
  jpa:
    hibernate:
      # 데이터베이스의 스키마와 jpa 엔티티가 불일치할때 애플리케이션 실행 중단
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    #마이그레이션 파일 경로
    locations: classpath:db/migration


openai:
  api:
    key: ${OPENAI_API_KEY}
    url: ${OPENAI_API_URL}

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: never
  jpa:
    hibernate:
      # 데이터베이스의 스키마와 jpa 엔티티가 불일치할때 애플리케이션 실행 중단
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    #마이그레이션 파일 경로
    locations: classpath:db/migration

#
openai:
  api:
    key: ${OPENAI_API_KEY}
    url: ${OPENAI_API_URL}
